/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAppointmentLogRouteImport } from './routes/_authenticated/appointment-log'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFormsRouteImport } from './routes/_authenticated/forms'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedModulesExplorerRouteImport } from './routes/_authenticated/modules-explorer'
import { Route as AuthenticatedOpportunitiesRouteImport } from './routes/_authenticated/opportunities'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated/workflows'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedContactsIndexRouteImport } from './routes/_authenticated/contacts.index'
import { Route as AuthenticatedContactsIdRouteImport } from './routes/_authenticated/contacts.$id'
import { Route as AuthenticatedDealsIdRouteImport } from './routes/_authenticated/deals.$id'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices.index'
import { Route as AuthenticatedInvoicesIdRouteImport } from './routes/_authenticated/invoices.$id'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedSettingsAiAssistantRouteImport } from './routes/_authenticated/settings.ai-assistant'
import { Route as AuthenticatedSettingsAppReviewRouteImport } from './routes/_authenticated/settings.app-review'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings.appearance'
import { Route as AuthenticatedSettingsBookingRouteImport } from './routes/_authenticated/settings.booking'
import { Route as AuthenticatedSettingsCallFlowsRouteImport } from './routes/_authenticated/settings.call-flows'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings.integrations'
import { Route as AuthenticatedSettingsInvoicesRouteImport } from './routes/_authenticated/settings.invoices'
import { Route as AuthenticatedSettingsMessagingRouteImport } from './routes/_authenticated/settings.messaging'
import { Route as AuthenticatedSettingsModulesRouteImport } from './routes/_authenticated/settings.modules'
import { Route as AuthenticatedSettingsPhoneNumbersRouteImport } from './routes/_authenticated/settings.phone-numbers'
import { Route as AuthenticatedSettingsSignupsRouteImport } from './routes/_authenticated/settings.signups'
import { Route as AuthenticatedSettingsSubAccountsRouteImport } from './routes/_authenticated/settings.sub-accounts'
import { Route as AuthenticatedSettingsSubscriptionsRouteImport } from './routes/_authenticated/settings.subscriptions'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings.team'
import { Route as AuthenticatedSettingsWordpressRouteImport } from './routes/_authenticated/settings.wordpress'
import { Route as ApiPublicProcessOutboundRouteImport } from './routes/api/public/process-outbound'
import { Route as ApiPublicBookingSlugRouteImport } from './routes/api/public/booking.$slug'
import { Route as ApiPublicFormsSlugRouteImport } from './routes/api/public/forms.$slug'
import { Route as ApiPublicHooksAppointmentsRouteImport } from './routes/api/public/hooks/appointments'
import { Route as ApiPublicHooksSyncGoogleAdsRouteImport } from './routes/api/public/hooks/sync-google-ads'
import { Route as ApiPublicInvoicesRemindersRouteImport } from './routes/api/public/invoices/reminders'
import { Route as ApiPublicLSlugRouteImport } from './routes/api/public/l.$slug'
import { Route as ApiPublicMetaDataDeletionRouteImport } from './routes/api/public/meta.data-deletion'
import { Route as ApiPublicPaymentsReconcileRouteImport } from './routes/api/public/payments/reconcile'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicBookingRescheduleTokenRouteImport } from './routes/api/public/booking.reschedule.$token'
import { Route as ApiPublicHooksMetaTokenRouteImport } from './routes/api/public/hooks/meta.$token'
import { Route as ApiPublicHooksWordpressTokenRouteImport } from './routes/api/public/hooks/wordpress.$token'
import { Route as ApiPublicOauthGoogleAdsCallbackRouteImport } from './routes/api/public/oauth.google-ads.callback'
import { Route as ApiPublicOauthMetaCallbackRouteImport } from './routes/api/public/oauth.meta.callback'
import { Route as ApiPublicTwilioTokenRecordingRouteImport } from './routes/api/public/twilio.$token.recording'
import { Route as ApiPublicTwilioTokenSmsRouteImport } from './routes/api/public/twilio.$token.sms'
import { Route as ApiPublicTwilioTokenStatusRouteImport } from './routes/api/public/twilio.$token.status'
import { Route as ApiPublicTwilioTokenVoiceRouteImport } from './routes/api/public/twilio.$token.voice'
import { Route as ApiPublicTwilioTokenVoiceOutboundRouteImport } from './routes/api/public/twilio.$token.voice-outbound'
import { Route as ApiPublicTwilioTokenVoiceStatusRouteImport } from './routes/api/public/twilio.$token.voice-status'
import { Route as ApiPublicTwilioTokenVoicemailRouteImport } from './routes/api/public/twilio.$token.voicemail'
import { Route as ApiPublicTwilioTokenWhatsappRouteImport } from './routes/api/public/twilio.$token.whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppointmentLogRoute =
  AuthenticatedAppointmentLogRouteImport.update({
    id: '/appointment-log',
    path: '/appointment-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormsRoute = AuthenticatedFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModulesExplorerRoute =
  AuthenticatedModulesExplorerRouteImport.update({
    id: '/modules-explorer',
    path: '/modules-explorer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpportunitiesRoute =
  AuthenticatedOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContactsIndexRoute =
  AuthenticatedContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsIdRoute = AuthenticatedContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsIdRoute = AuthenticatedDealsIdRouteImport.update({
  id: '/deals/$id',
  path: '/deals/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIdRoute = AuthenticatedInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAiAssistantRoute =
  AuthenticatedSettingsAiAssistantRouteImport.update({
    id: '/settings/ai-assistant',
    path: '/settings/ai-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAppReviewRoute =
  AuthenticatedSettingsAppReviewRouteImport.update({
    id: '/settings/app-review',
    path: '/settings/app-review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/settings/appearance',
    path: '/settings/appearance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsBookingRoute =
  AuthenticatedSettingsBookingRouteImport.update({
    id: '/settings/booking',
    path: '/settings/booking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCallFlowsRoute =
  AuthenticatedSettingsCallFlowsRouteImport.update({
    id: '/settings/call-flows',
    path: '/settings/call-flows',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsInvoicesRoute =
  AuthenticatedSettingsInvoicesRouteImport.update({
    id: '/settings/invoices',
    path: '/settings/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsMessagingRoute =
  AuthenticatedSettingsMessagingRouteImport.update({
    id: '/settings/messaging',
    path: '/settings/messaging',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsModulesRoute =
  AuthenticatedSettingsModulesRouteImport.update({
    id: '/settings/modules',
    path: '/settings/modules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPhoneNumbersRoute =
  AuthenticatedSettingsPhoneNumbersRouteImport.update({
    id: '/settings/phone-numbers',
    path: '/settings/phone-numbers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSignupsRoute =
  AuthenticatedSettingsSignupsRouteImport.update({
    id: '/settings/signups',
    path: '/settings/signups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSubAccountsRoute =
  AuthenticatedSettingsSubAccountsRouteImport.update({
    id: '/settings/sub-accounts',
    path: '/settings/sub-accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSubscriptionsRoute =
  AuthenticatedSettingsSubscriptionsRouteImport.update({
    id: '/settings/subscriptions',
    path: '/settings/subscriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/settings/team',
    path: '/settings/team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsWordpressRoute =
  AuthenticatedSettingsWordpressRouteImport.update({
    id: '/settings/wordpress',
    path: '/settings/wordpress',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicProcessOutboundRoute =
  ApiPublicProcessOutboundRouteImport.update({
    id: '/api/public/process-outbound',
    path: '/api/public/process-outbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBookingSlugRoute = ApiPublicBookingSlugRouteImport.update({
  id: '/api/public/booking/$slug',
  path: '/api/public/booking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFormsSlugRoute = ApiPublicFormsSlugRouteImport.update({
  id: '/api/public/forms/$slug',
  path: '/api/public/forms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAppointmentsRoute =
  ApiPublicHooksAppointmentsRouteImport.update({
    id: '/api/public/hooks/appointments',
    path: '/api/public/hooks/appointments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncGoogleAdsRoute =
  ApiPublicHooksSyncGoogleAdsRouteImport.update({
    id: '/api/public/hooks/sync-google-ads',
    path: '/api/public/hooks/sync-google-ads',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInvoicesRemindersRoute =
  ApiPublicInvoicesRemindersRouteImport.update({
    id: '/api/public/invoices/reminders',
    path: '/api/public/invoices/reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLSlugRoute = ApiPublicLSlugRouteImport.update({
  id: '/api/public/l/$slug',
  path: '/api/public/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaDataDeletionRoute =
  ApiPublicMetaDataDeletionRouteImport.update({
    id: '/api/public/meta/data-deletion',
    path: '/api/public/meta/data-deletion',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsReconcileRoute =
  ApiPublicPaymentsReconcileRouteImport.update({
    id: '/api/public/payments/reconcile',
    path: '/api/public/payments/reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBookingRescheduleTokenRoute =
  ApiPublicBookingRescheduleTokenRouteImport.update({
    id: '/api/public/booking/reschedule/$token',
    path: '/api/public/booking/reschedule/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMetaTokenRoute = ApiPublicHooksMetaTokenRouteImport.update({
  id: '/api/public/hooks/meta/$token',
  path: '/api/public/hooks/meta/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWordpressTokenRoute =
  ApiPublicHooksWordpressTokenRouteImport.update({
    id: '/api/public/hooks/wordpress/$token',
    path: '/api/public/hooks/wordpress/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthGoogleAdsCallbackRoute =
  ApiPublicOauthGoogleAdsCallbackRouteImport.update({
    id: '/api/public/oauth/google-ads/callback',
    path: '/api/public/oauth/google-ads/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthMetaCallbackRoute =
  ApiPublicOauthMetaCallbackRouteImport.update({
    id: '/api/public/oauth/meta/callback',
    path: '/api/public/oauth/meta/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioTokenRecordingRoute =
  ApiPublicTwilioTokenRecordingRouteImport.update({
    id: '/api/public/twilio/$token/recording',
    path: '/api/public/twilio/$token/recording',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioTokenSmsRoute = ApiPublicTwilioTokenSmsRouteImport.update({
  id: '/api/public/twilio/$token/sms',
  path: '/api/public/twilio/$token/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioTokenStatusRoute =
  ApiPublicTwilioTokenStatusRouteImport.update({
    id: '/api/public/twilio/$token/status',
    path: '/api/public/twilio/$token/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioTokenVoiceRoute =
  ApiPublicTwilioTokenVoiceRouteImport.update({
    id: '/api/public/twilio/$token/voice',
    path: '/api/public/twilio/$token/voice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioTokenVoiceOutboundRoute =
  ApiPublicTwilioTokenVoiceOutboundRouteImport.update({
    id: '/api/public/twilio/$token/voice-outbound',
    path: '/api/public/twilio/$token/voice-outbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioTokenVoiceStatusRoute =
  ApiPublicTwilioTokenVoiceStatusRouteImport.update({
    id: '/api/public/twilio/$token/voice-status',
    path: '/api/public/twilio/$token/voice-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioTokenVoicemailRoute =
  ApiPublicTwilioTokenVoicemailRouteImport.update({
    id: '/api/public/twilio/$token/voicemail',
    path: '/api/public/twilio/$token/voicemail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioTokenWhatsappRoute =
  ApiPublicTwilioTokenWhatsappRouteImport.update({
    id: '/api/public/twilio/$token/whatsapp',
    path: '/api/public/twilio/$token/whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/appointment-log': typeof AuthenticatedAppointmentLogRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forms': typeof AuthenticatedFormsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/modules-explorer': typeof AuthenticatedModulesExplorerRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/b/$slug': typeof BSlugRoute
  '/f/$slug': typeof FSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/settings/ai-assistant': typeof AuthenticatedSettingsAiAssistantRoute
  '/settings/app-review': typeof AuthenticatedSettingsAppReviewRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/booking': typeof AuthenticatedSettingsBookingRoute
  '/settings/call-flows': typeof AuthenticatedSettingsCallFlowsRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/invoices': typeof AuthenticatedSettingsInvoicesRoute
  '/settings/messaging': typeof AuthenticatedSettingsMessagingRoute
  '/settings/modules': typeof AuthenticatedSettingsModulesRoute
  '/settings/phone-numbers': typeof AuthenticatedSettingsPhoneNumbersRoute
  '/settings/signups': typeof AuthenticatedSettingsSignupsRoute
  '/settings/sub-accounts': typeof AuthenticatedSettingsSubAccountsRoute
  '/settings/subscriptions': typeof AuthenticatedSettingsSubscriptionsRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/settings/wordpress': typeof AuthenticatedSettingsWordpressRoute
  '/api/public/process-outbound': typeof ApiPublicProcessOutboundRoute
  '/contacts/': typeof AuthenticatedContactsIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/booking/$slug': typeof ApiPublicBookingSlugRoute
  '/api/public/forms/$slug': typeof ApiPublicFormsSlugRoute
  '/api/public/hooks/appointments': typeof ApiPublicHooksAppointmentsRoute
  '/api/public/hooks/sync-google-ads': typeof ApiPublicHooksSyncGoogleAdsRoute
  '/api/public/invoices/reminders': typeof ApiPublicInvoicesRemindersRoute
  '/api/public/l/$slug': typeof ApiPublicLSlugRoute
  '/api/public/meta/data-deletion': typeof ApiPublicMetaDataDeletionRoute
  '/api/public/payments/reconcile': typeof ApiPublicPaymentsReconcileRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/booking/reschedule/$token': typeof ApiPublicBookingRescheduleTokenRoute
  '/api/public/hooks/meta/$token': typeof ApiPublicHooksMetaTokenRoute
  '/api/public/hooks/wordpress/$token': typeof ApiPublicHooksWordpressTokenRoute
  '/api/public/oauth/google-ads/callback': typeof ApiPublicOauthGoogleAdsCallbackRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
  '/api/public/twilio/$token/recording': typeof ApiPublicTwilioTokenRecordingRoute
  '/api/public/twilio/$token/sms': typeof ApiPublicTwilioTokenSmsRoute
  '/api/public/twilio/$token/status': typeof ApiPublicTwilioTokenStatusRoute
  '/api/public/twilio/$token/voice': typeof ApiPublicTwilioTokenVoiceRoute
  '/api/public/twilio/$token/voice-outbound': typeof ApiPublicTwilioTokenVoiceOutboundRoute
  '/api/public/twilio/$token/voice-status': typeof ApiPublicTwilioTokenVoiceStatusRoute
  '/api/public/twilio/$token/voicemail': typeof ApiPublicTwilioTokenVoicemailRoute
  '/api/public/twilio/$token/whatsapp': typeof ApiPublicTwilioTokenWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/appointment-log': typeof AuthenticatedAppointmentLogRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forms': typeof AuthenticatedFormsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/modules-explorer': typeof AuthenticatedModulesExplorerRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/b/$slug': typeof BSlugRoute
  '/f/$slug': typeof FSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/settings/ai-assistant': typeof AuthenticatedSettingsAiAssistantRoute
  '/settings/app-review': typeof AuthenticatedSettingsAppReviewRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/booking': typeof AuthenticatedSettingsBookingRoute
  '/settings/call-flows': typeof AuthenticatedSettingsCallFlowsRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/invoices': typeof AuthenticatedSettingsInvoicesRoute
  '/settings/messaging': typeof AuthenticatedSettingsMessagingRoute
  '/settings/modules': typeof AuthenticatedSettingsModulesRoute
  '/settings/phone-numbers': typeof AuthenticatedSettingsPhoneNumbersRoute
  '/settings/signups': typeof AuthenticatedSettingsSignupsRoute
  '/settings/sub-accounts': typeof AuthenticatedSettingsSubAccountsRoute
  '/settings/subscriptions': typeof AuthenticatedSettingsSubscriptionsRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/settings/wordpress': typeof AuthenticatedSettingsWordpressRoute
  '/api/public/process-outbound': typeof ApiPublicProcessOutboundRoute
  '/contacts': typeof AuthenticatedContactsIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/api/public/booking/$slug': typeof ApiPublicBookingSlugRoute
  '/api/public/forms/$slug': typeof ApiPublicFormsSlugRoute
  '/api/public/hooks/appointments': typeof ApiPublicHooksAppointmentsRoute
  '/api/public/hooks/sync-google-ads': typeof ApiPublicHooksSyncGoogleAdsRoute
  '/api/public/invoices/reminders': typeof ApiPublicInvoicesRemindersRoute
  '/api/public/l/$slug': typeof ApiPublicLSlugRoute
  '/api/public/meta/data-deletion': typeof ApiPublicMetaDataDeletionRoute
  '/api/public/payments/reconcile': typeof ApiPublicPaymentsReconcileRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/booking/reschedule/$token': typeof ApiPublicBookingRescheduleTokenRoute
  '/api/public/hooks/meta/$token': typeof ApiPublicHooksMetaTokenRoute
  '/api/public/hooks/wordpress/$token': typeof ApiPublicHooksWordpressTokenRoute
  '/api/public/oauth/google-ads/callback': typeof ApiPublicOauthGoogleAdsCallbackRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
  '/api/public/twilio/$token/recording': typeof ApiPublicTwilioTokenRecordingRoute
  '/api/public/twilio/$token/sms': typeof ApiPublicTwilioTokenSmsRoute
  '/api/public/twilio/$token/status': typeof ApiPublicTwilioTokenStatusRoute
  '/api/public/twilio/$token/voice': typeof ApiPublicTwilioTokenVoiceRoute
  '/api/public/twilio/$token/voice-outbound': typeof ApiPublicTwilioTokenVoiceOutboundRoute
  '/api/public/twilio/$token/voice-status': typeof ApiPublicTwilioTokenVoiceStatusRoute
  '/api/public/twilio/$token/voicemail': typeof ApiPublicTwilioTokenVoicemailRoute
  '/api/public/twilio/$token/whatsapp': typeof ApiPublicTwilioTokenWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/appointment-log': typeof AuthenticatedAppointmentLogRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/conversations': typeof AuthenticatedConversationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/forms': typeof AuthenticatedFormsRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/modules-explorer': typeof AuthenticatedModulesExplorerRoute
  '/_authenticated/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRoute
  '/b/$slug': typeof BSlugRoute
  '/f/$slug': typeof FSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/_authenticated/deals/$id': typeof AuthenticatedDealsIdRoute
  '/_authenticated/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/_authenticated/settings/ai-assistant': typeof AuthenticatedSettingsAiAssistantRoute
  '/_authenticated/settings/app-review': typeof AuthenticatedSettingsAppReviewRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/booking': typeof AuthenticatedSettingsBookingRoute
  '/_authenticated/settings/call-flows': typeof AuthenticatedSettingsCallFlowsRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/invoices': typeof AuthenticatedSettingsInvoicesRoute
  '/_authenticated/settings/messaging': typeof AuthenticatedSettingsMessagingRoute
  '/_authenticated/settings/modules': typeof AuthenticatedSettingsModulesRoute
  '/_authenticated/settings/phone-numbers': typeof AuthenticatedSettingsPhoneNumbersRoute
  '/_authenticated/settings/signups': typeof AuthenticatedSettingsSignupsRoute
  '/_authenticated/settings/sub-accounts': typeof AuthenticatedSettingsSubAccountsRoute
  '/_authenticated/settings/subscriptions': typeof AuthenticatedSettingsSubscriptionsRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/settings/wordpress': typeof AuthenticatedSettingsWordpressRoute
  '/api/public/process-outbound': typeof ApiPublicProcessOutboundRoute
  '/_authenticated/contacts/': typeof AuthenticatedContactsIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/public/booking/$slug': typeof ApiPublicBookingSlugRoute
  '/api/public/forms/$slug': typeof ApiPublicFormsSlugRoute
  '/api/public/hooks/appointments': typeof ApiPublicHooksAppointmentsRoute
  '/api/public/hooks/sync-google-ads': typeof ApiPublicHooksSyncGoogleAdsRoute
  '/api/public/invoices/reminders': typeof ApiPublicInvoicesRemindersRoute
  '/api/public/l/$slug': typeof ApiPublicLSlugRoute
  '/api/public/meta/data-deletion': typeof ApiPublicMetaDataDeletionRoute
  '/api/public/payments/reconcile': typeof ApiPublicPaymentsReconcileRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/booking/reschedule/$token': typeof ApiPublicBookingRescheduleTokenRoute
  '/api/public/hooks/meta/$token': typeof ApiPublicHooksMetaTokenRoute
  '/api/public/hooks/wordpress/$token': typeof ApiPublicHooksWordpressTokenRoute
  '/api/public/oauth/google-ads/callback': typeof ApiPublicOauthGoogleAdsCallbackRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
  '/api/public/twilio/$token/recording': typeof ApiPublicTwilioTokenRecordingRoute
  '/api/public/twilio/$token/sms': typeof ApiPublicTwilioTokenSmsRoute
  '/api/public/twilio/$token/status': typeof ApiPublicTwilioTokenStatusRoute
  '/api/public/twilio/$token/voice': typeof ApiPublicTwilioTokenVoiceRoute
  '/api/public/twilio/$token/voice-outbound': typeof ApiPublicTwilioTokenVoiceOutboundRoute
  '/api/public/twilio/$token/voice-status': typeof ApiPublicTwilioTokenVoiceStatusRoute
  '/api/public/twilio/$token/voicemail': typeof ApiPublicTwilioTokenVoicemailRoute
  '/api/public/twilio/$token/whatsapp': typeof ApiPublicTwilioTokenWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/appointment-log'
    | '/calendar'
    | '/calls'
    | '/conversations'
    | '/dashboard'
    | '/forms'
    | '/inbox'
    | '/marketing'
    | '/modules-explorer'
    | '/opportunities'
    | '/reports'
    | '/tasks'
    | '/templates'
    | '/workflows'
    | '/b/$slug'
    | '/f/$slug'
    | '/invite/$token'
    | '/contacts/$id'
    | '/deals/$id'
    | '/invoices/$id'
    | '/settings/ai-assistant'
    | '/settings/app-review'
    | '/settings/appearance'
    | '/settings/booking'
    | '/settings/call-flows'
    | '/settings/integrations'
    | '/settings/invoices'
    | '/settings/messaging'
    | '/settings/modules'
    | '/settings/phone-numbers'
    | '/settings/signups'
    | '/settings/sub-accounts'
    | '/settings/subscriptions'
    | '/settings/team'
    | '/settings/wordpress'
    | '/api/public/process-outbound'
    | '/contacts/'
    | '/invoices/'
    | '/settings/'
    | '/api/public/booking/$slug'
    | '/api/public/forms/$slug'
    | '/api/public/hooks/appointments'
    | '/api/public/hooks/sync-google-ads'
    | '/api/public/invoices/reminders'
    | '/api/public/l/$slug'
    | '/api/public/meta/data-deletion'
    | '/api/public/payments/reconcile'
    | '/api/public/payments/webhook'
    | '/api/public/booking/reschedule/$token'
    | '/api/public/hooks/meta/$token'
    | '/api/public/hooks/wordpress/$token'
    | '/api/public/oauth/google-ads/callback'
    | '/api/public/oauth/meta/callback'
    | '/api/public/twilio/$token/recording'
    | '/api/public/twilio/$token/sms'
    | '/api/public/twilio/$token/status'
    | '/api/public/twilio/$token/voice'
    | '/api/public/twilio/$token/voice-outbound'
    | '/api/public/twilio/$token/voice-status'
    | '/api/public/twilio/$token/voicemail'
    | '/api/public/twilio/$token/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/appointment-log'
    | '/calendar'
    | '/calls'
    | '/conversations'
    | '/dashboard'
    | '/forms'
    | '/inbox'
    | '/marketing'
    | '/modules-explorer'
    | '/opportunities'
    | '/reports'
    | '/tasks'
    | '/templates'
    | '/workflows'
    | '/b/$slug'
    | '/f/$slug'
    | '/invite/$token'
    | '/contacts/$id'
    | '/deals/$id'
    | '/invoices/$id'
    | '/settings/ai-assistant'
    | '/settings/app-review'
    | '/settings/appearance'
    | '/settings/booking'
    | '/settings/call-flows'
    | '/settings/integrations'
    | '/settings/invoices'
    | '/settings/messaging'
    | '/settings/modules'
    | '/settings/phone-numbers'
    | '/settings/signups'
    | '/settings/sub-accounts'
    | '/settings/subscriptions'
    | '/settings/team'
    | '/settings/wordpress'
    | '/api/public/process-outbound'
    | '/contacts'
    | '/invoices'
    | '/settings'
    | '/api/public/booking/$slug'
    | '/api/public/forms/$slug'
    | '/api/public/hooks/appointments'
    | '/api/public/hooks/sync-google-ads'
    | '/api/public/invoices/reminders'
    | '/api/public/l/$slug'
    | '/api/public/meta/data-deletion'
    | '/api/public/payments/reconcile'
    | '/api/public/payments/webhook'
    | '/api/public/booking/reschedule/$token'
    | '/api/public/hooks/meta/$token'
    | '/api/public/hooks/wordpress/$token'
    | '/api/public/oauth/google-ads/callback'
    | '/api/public/oauth/meta/callback'
    | '/api/public/twilio/$token/recording'
    | '/api/public/twilio/$token/sms'
    | '/api/public/twilio/$token/status'
    | '/api/public/twilio/$token/voice'
    | '/api/public/twilio/$token/voice-outbound'
    | '/api/public/twilio/$token/voice-status'
    | '/api/public/twilio/$token/voicemail'
    | '/api/public/twilio/$token/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/data-deletion'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/_authenticated/appointment-log'
    | '/_authenticated/calendar'
    | '/_authenticated/calls'
    | '/_authenticated/conversations'
    | '/_authenticated/dashboard'
    | '/_authenticated/forms'
    | '/_authenticated/inbox'
    | '/_authenticated/marketing'
    | '/_authenticated/modules-explorer'
    | '/_authenticated/opportunities'
    | '/_authenticated/reports'
    | '/_authenticated/tasks'
    | '/_authenticated/templates'
    | '/_authenticated/workflows'
    | '/b/$slug'
    | '/f/$slug'
    | '/invite/$token'
    | '/_authenticated/contacts/$id'
    | '/_authenticated/deals/$id'
    | '/_authenticated/invoices/$id'
    | '/_authenticated/settings/ai-assistant'
    | '/_authenticated/settings/app-review'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/booking'
    | '/_authenticated/settings/call-flows'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/invoices'
    | '/_authenticated/settings/messaging'
    | '/_authenticated/settings/modules'
    | '/_authenticated/settings/phone-numbers'
    | '/_authenticated/settings/signups'
    | '/_authenticated/settings/sub-accounts'
    | '/_authenticated/settings/subscriptions'
    | '/_authenticated/settings/team'
    | '/_authenticated/settings/wordpress'
    | '/api/public/process-outbound'
    | '/_authenticated/contacts/'
    | '/_authenticated/invoices/'
    | '/_authenticated/settings/'
    | '/api/public/booking/$slug'
    | '/api/public/forms/$slug'
    | '/api/public/hooks/appointments'
    | '/api/public/hooks/sync-google-ads'
    | '/api/public/invoices/reminders'
    | '/api/public/l/$slug'
    | '/api/public/meta/data-deletion'
    | '/api/public/payments/reconcile'
    | '/api/public/payments/webhook'
    | '/api/public/booking/reschedule/$token'
    | '/api/public/hooks/meta/$token'
    | '/api/public/hooks/wordpress/$token'
    | '/api/public/oauth/google-ads/callback'
    | '/api/public/oauth/meta/callback'
    | '/api/public/twilio/$token/recording'
    | '/api/public/twilio/$token/sms'
    | '/api/public/twilio/$token/status'
    | '/api/public/twilio/$token/voice'
    | '/api/public/twilio/$token/voice-outbound'
    | '/api/public/twilio/$token/voice-status'
    | '/api/public/twilio/$token/voicemail'
    | '/api/public/twilio/$token/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DataDeletionRoute: typeof DataDeletionRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  BSlugRoute: typeof BSlugRoute
  FSlugRoute: typeof FSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicProcessOutboundRoute: typeof ApiPublicProcessOutboundRoute
  ApiPublicBookingSlugRoute: typeof ApiPublicBookingSlugRoute
  ApiPublicFormsSlugRoute: typeof ApiPublicFormsSlugRoute
  ApiPublicHooksAppointmentsRoute: typeof ApiPublicHooksAppointmentsRoute
  ApiPublicHooksSyncGoogleAdsRoute: typeof ApiPublicHooksSyncGoogleAdsRoute
  ApiPublicInvoicesRemindersRoute: typeof ApiPublicInvoicesRemindersRoute
  ApiPublicLSlugRoute: typeof ApiPublicLSlugRoute
  ApiPublicMetaDataDeletionRoute: typeof ApiPublicMetaDataDeletionRoute
  ApiPublicPaymentsReconcileRoute: typeof ApiPublicPaymentsReconcileRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicBookingRescheduleTokenRoute: typeof ApiPublicBookingRescheduleTokenRoute
  ApiPublicHooksMetaTokenRoute: typeof ApiPublicHooksMetaTokenRoute
  ApiPublicHooksWordpressTokenRoute: typeof ApiPublicHooksWordpressTokenRoute
  ApiPublicOauthGoogleAdsCallbackRoute: typeof ApiPublicOauthGoogleAdsCallbackRoute
  ApiPublicOauthMetaCallbackRoute: typeof ApiPublicOauthMetaCallbackRoute
  ApiPublicTwilioTokenRecordingRoute: typeof ApiPublicTwilioTokenRecordingRoute
  ApiPublicTwilioTokenSmsRoute: typeof ApiPublicTwilioTokenSmsRoute
  ApiPublicTwilioTokenStatusRoute: typeof ApiPublicTwilioTokenStatusRoute
  ApiPublicTwilioTokenVoiceRoute: typeof ApiPublicTwilioTokenVoiceRoute
  ApiPublicTwilioTokenVoiceOutboundRoute: typeof ApiPublicTwilioTokenVoiceOutboundRoute
  ApiPublicTwilioTokenVoiceStatusRoute: typeof ApiPublicTwilioTokenVoiceStatusRoute
  ApiPublicTwilioTokenVoicemailRoute: typeof ApiPublicTwilioTokenVoicemailRoute
  ApiPublicTwilioTokenWhatsappRoute: typeof ApiPublicTwilioTokenWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appointment-log': {
      id: '/_authenticated/appointment-log'
      path: '/appointment-log'
      fullPath: '/appointment-log'
      preLoaderRoute: typeof AuthenticatedAppointmentLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms': {
      id: '/_authenticated/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AuthenticatedFormsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules-explorer': {
      id: '/_authenticated/modules-explorer'
      path: '/modules-explorer'
      fullPath: '/modules-explorer'
      preLoaderRoute: typeof AuthenticatedModulesExplorerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opportunities': {
      id: '/_authenticated/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthenticatedOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contacts/': {
      id: '/_authenticated/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthenticatedContactsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/$id': {
      id: '/_authenticated/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AuthenticatedContactsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals/$id': {
      id: '/_authenticated/deals/$id'
      path: '/deals/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof AuthenticatedDealsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$id': {
      id: '/_authenticated/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthenticatedInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/ai-assistant': {
      id: '/_authenticated/settings/ai-assistant'
      path: '/settings/ai-assistant'
      fullPath: '/settings/ai-assistant'
      preLoaderRoute: typeof AuthenticatedSettingsAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/app-review': {
      id: '/_authenticated/settings/app-review'
      path: '/settings/app-review'
      fullPath: '/settings/app-review'
      preLoaderRoute: typeof AuthenticatedSettingsAppReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/booking': {
      id: '/_authenticated/settings/booking'
      path: '/settings/booking'
      fullPath: '/settings/booking'
      preLoaderRoute: typeof AuthenticatedSettingsBookingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/call-flows': {
      id: '/_authenticated/settings/call-flows'
      path: '/settings/call-flows'
      fullPath: '/settings/call-flows'
      preLoaderRoute: typeof AuthenticatedSettingsCallFlowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/invoices': {
      id: '/_authenticated/settings/invoices'
      path: '/settings/invoices'
      fullPath: '/settings/invoices'
      preLoaderRoute: typeof AuthenticatedSettingsInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/messaging': {
      id: '/_authenticated/settings/messaging'
      path: '/settings/messaging'
      fullPath: '/settings/messaging'
      preLoaderRoute: typeof AuthenticatedSettingsMessagingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/modules': {
      id: '/_authenticated/settings/modules'
      path: '/settings/modules'
      fullPath: '/settings/modules'
      preLoaderRoute: typeof AuthenticatedSettingsModulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/phone-numbers': {
      id: '/_authenticated/settings/phone-numbers'
      path: '/settings/phone-numbers'
      fullPath: '/settings/phone-numbers'
      preLoaderRoute: typeof AuthenticatedSettingsPhoneNumbersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/signups': {
      id: '/_authenticated/settings/signups'
      path: '/settings/signups'
      fullPath: '/settings/signups'
      preLoaderRoute: typeof AuthenticatedSettingsSignupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/sub-accounts': {
      id: '/_authenticated/settings/sub-accounts'
      path: '/settings/sub-accounts'
      fullPath: '/settings/sub-accounts'
      preLoaderRoute: typeof AuthenticatedSettingsSubAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/subscriptions': {
      id: '/_authenticated/settings/subscriptions'
      path: '/settings/subscriptions'
      fullPath: '/settings/subscriptions'
      preLoaderRoute: typeof AuthenticatedSettingsSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/wordpress': {
      id: '/_authenticated/settings/wordpress'
      path: '/settings/wordpress'
      fullPath: '/settings/wordpress'
      preLoaderRoute: typeof AuthenticatedSettingsWordpressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/process-outbound': {
      id: '/api/public/process-outbound'
      path: '/api/public/process-outbound'
      fullPath: '/api/public/process-outbound'
      preLoaderRoute: typeof ApiPublicProcessOutboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking/$slug': {
      id: '/api/public/booking/$slug'
      path: '/api/public/booking/$slug'
      fullPath: '/api/public/booking/$slug'
      preLoaderRoute: typeof ApiPublicBookingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forms/$slug': {
      id: '/api/public/forms/$slug'
      path: '/api/public/forms/$slug'
      fullPath: '/api/public/forms/$slug'
      preLoaderRoute: typeof ApiPublicFormsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/appointments': {
      id: '/api/public/hooks/appointments'
      path: '/api/public/hooks/appointments'
      fullPath: '/api/public/hooks/appointments'
      preLoaderRoute: typeof ApiPublicHooksAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-google-ads': {
      id: '/api/public/hooks/sync-google-ads'
      path: '/api/public/hooks/sync-google-ads'
      fullPath: '/api/public/hooks/sync-google-ads'
      preLoaderRoute: typeof ApiPublicHooksSyncGoogleAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/invoices/reminders': {
      id: '/api/public/invoices/reminders'
      path: '/api/public/invoices/reminders'
      fullPath: '/api/public/invoices/reminders'
      preLoaderRoute: typeof ApiPublicInvoicesRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/l/$slug': {
      id: '/api/public/l/$slug'
      path: '/api/public/l/$slug'
      fullPath: '/api/public/l/$slug'
      preLoaderRoute: typeof ApiPublicLSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/data-deletion': {
      id: '/api/public/meta/data-deletion'
      path: '/api/public/meta/data-deletion'
      fullPath: '/api/public/meta/data-deletion'
      preLoaderRoute: typeof ApiPublicMetaDataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/reconcile': {
      id: '/api/public/payments/reconcile'
      path: '/api/public/payments/reconcile'
      fullPath: '/api/public/payments/reconcile'
      preLoaderRoute: typeof ApiPublicPaymentsReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking/reschedule/$token': {
      id: '/api/public/booking/reschedule/$token'
      path: '/api/public/booking/reschedule/$token'
      fullPath: '/api/public/booking/reschedule/$token'
      preLoaderRoute: typeof ApiPublicBookingRescheduleTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/meta/$token': {
      id: '/api/public/hooks/meta/$token'
      path: '/api/public/hooks/meta/$token'
      fullPath: '/api/public/hooks/meta/$token'
      preLoaderRoute: typeof ApiPublicHooksMetaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/wordpress/$token': {
      id: '/api/public/hooks/wordpress/$token'
      path: '/api/public/hooks/wordpress/$token'
      fullPath: '/api/public/hooks/wordpress/$token'
      preLoaderRoute: typeof ApiPublicHooksWordpressTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/google-ads/callback': {
      id: '/api/public/oauth/google-ads/callback'
      path: '/api/public/oauth/google-ads/callback'
      fullPath: '/api/public/oauth/google-ads/callback'
      preLoaderRoute: typeof ApiPublicOauthGoogleAdsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/meta/callback': {
      id: '/api/public/oauth/meta/callback'
      path: '/api/public/oauth/meta/callback'
      fullPath: '/api/public/oauth/meta/callback'
      preLoaderRoute: typeof ApiPublicOauthMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/$token/recording': {
      id: '/api/public/twilio/$token/recording'
      path: '/api/public/twilio/$token/recording'
      fullPath: '/api/public/twilio/$token/recording'
      preLoaderRoute: typeof ApiPublicTwilioTokenRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/$token/sms': {
      id: '/api/public/twilio/$token/sms'
      path: '/api/public/twilio/$token/sms'
      fullPath: '/api/public/twilio/$token/sms'
      preLoaderRoute: typeof ApiPublicTwilioTokenSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/$token/status': {
      id: '/api/public/twilio/$token/status'
      path: '/api/public/twilio/$token/status'
      fullPath: '/api/public/twilio/$token/status'
      preLoaderRoute: typeof ApiPublicTwilioTokenStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/$token/voice': {
      id: '/api/public/twilio/$token/voice'
      path: '/api/public/twilio/$token/voice'
      fullPath: '/api/public/twilio/$token/voice'
      preLoaderRoute: typeof ApiPublicTwilioTokenVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/$token/voice-outbound': {
      id: '/api/public/twilio/$token/voice-outbound'
      path: '/api/public/twilio/$token/voice-outbound'
      fullPath: '/api/public/twilio/$token/voice-outbound'
      preLoaderRoute: typeof ApiPublicTwilioTokenVoiceOutboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/$token/voice-status': {
      id: '/api/public/twilio/$token/voice-status'
      path: '/api/public/twilio/$token/voice-status'
      fullPath: '/api/public/twilio/$token/voice-status'
      preLoaderRoute: typeof ApiPublicTwilioTokenVoiceStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/$token/voicemail': {
      id: '/api/public/twilio/$token/voicemail'
      path: '/api/public/twilio/$token/voicemail'
      fullPath: '/api/public/twilio/$token/voicemail'
      preLoaderRoute: typeof ApiPublicTwilioTokenVoicemailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/$token/whatsapp': {
      id: '/api/public/twilio/$token/whatsapp'
      path: '/api/public/twilio/$token/whatsapp'
      fullPath: '/api/public/twilio/$token/whatsapp'
      preLoaderRoute: typeof ApiPublicTwilioTokenWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentLogRoute: typeof AuthenticatedAppointmentLogRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFormsRoute: typeof AuthenticatedFormsRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedModulesExplorerRoute: typeof AuthenticatedModulesExplorerRoute
  AuthenticatedOpportunitiesRoute: typeof AuthenticatedOpportunitiesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRoute
  AuthenticatedContactsIdRoute: typeof AuthenticatedContactsIdRoute
  AuthenticatedDealsIdRoute: typeof AuthenticatedDealsIdRoute
  AuthenticatedInvoicesIdRoute: typeof AuthenticatedInvoicesIdRoute
  AuthenticatedSettingsAiAssistantRoute: typeof AuthenticatedSettingsAiAssistantRoute
  AuthenticatedSettingsAppReviewRoute: typeof AuthenticatedSettingsAppReviewRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsBookingRoute: typeof AuthenticatedSettingsBookingRoute
  AuthenticatedSettingsCallFlowsRoute: typeof AuthenticatedSettingsCallFlowsRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsInvoicesRoute: typeof AuthenticatedSettingsInvoicesRoute
  AuthenticatedSettingsMessagingRoute: typeof AuthenticatedSettingsMessagingRoute
  AuthenticatedSettingsModulesRoute: typeof AuthenticatedSettingsModulesRoute
  AuthenticatedSettingsPhoneNumbersRoute: typeof AuthenticatedSettingsPhoneNumbersRoute
  AuthenticatedSettingsSignupsRoute: typeof AuthenticatedSettingsSignupsRoute
  AuthenticatedSettingsSubAccountsRoute: typeof AuthenticatedSettingsSubAccountsRoute
  AuthenticatedSettingsSubscriptionsRoute: typeof AuthenticatedSettingsSubscriptionsRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedSettingsWordpressRoute: typeof AuthenticatedSettingsWordpressRoute
  AuthenticatedContactsIndexRoute: typeof AuthenticatedContactsIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentLogRoute: AuthenticatedAppointmentLogRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFormsRoute: AuthenticatedFormsRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedModulesExplorerRoute: AuthenticatedModulesExplorerRoute,
  AuthenticatedOpportunitiesRoute: AuthenticatedOpportunitiesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRoute,
  AuthenticatedContactsIdRoute: AuthenticatedContactsIdRoute,
  AuthenticatedDealsIdRoute: AuthenticatedDealsIdRoute,
  AuthenticatedInvoicesIdRoute: AuthenticatedInvoicesIdRoute,
  AuthenticatedSettingsAiAssistantRoute: AuthenticatedSettingsAiAssistantRoute,
  AuthenticatedSettingsAppReviewRoute: AuthenticatedSettingsAppReviewRoute,
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsBookingRoute: AuthenticatedSettingsBookingRoute,
  AuthenticatedSettingsCallFlowsRoute: AuthenticatedSettingsCallFlowsRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedSettingsInvoicesRoute: AuthenticatedSettingsInvoicesRoute,
  AuthenticatedSettingsMessagingRoute: AuthenticatedSettingsMessagingRoute,
  AuthenticatedSettingsModulesRoute: AuthenticatedSettingsModulesRoute,
  AuthenticatedSettingsPhoneNumbersRoute:
    AuthenticatedSettingsPhoneNumbersRoute,
  AuthenticatedSettingsSignupsRoute: AuthenticatedSettingsSignupsRoute,
  AuthenticatedSettingsSubAccountsRoute: AuthenticatedSettingsSubAccountsRoute,
  AuthenticatedSettingsSubscriptionsRoute:
    AuthenticatedSettingsSubscriptionsRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
  AuthenticatedSettingsWordpressRoute: AuthenticatedSettingsWordpressRoute,
  AuthenticatedContactsIndexRoute: AuthenticatedContactsIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DataDeletionRoute: DataDeletionRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  BSlugRoute: BSlugRoute,
  FSlugRoute: FSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicProcessOutboundRoute: ApiPublicProcessOutboundRoute,
  ApiPublicBookingSlugRoute: ApiPublicBookingSlugRoute,
  ApiPublicFormsSlugRoute: ApiPublicFormsSlugRoute,
  ApiPublicHooksAppointmentsRoute: ApiPublicHooksAppointmentsRoute,
  ApiPublicHooksSyncGoogleAdsRoute: ApiPublicHooksSyncGoogleAdsRoute,
  ApiPublicInvoicesRemindersRoute: ApiPublicInvoicesRemindersRoute,
  ApiPublicLSlugRoute: ApiPublicLSlugRoute,
  ApiPublicMetaDataDeletionRoute: ApiPublicMetaDataDeletionRoute,
  ApiPublicPaymentsReconcileRoute: ApiPublicPaymentsReconcileRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicBookingRescheduleTokenRoute: ApiPublicBookingRescheduleTokenRoute,
  ApiPublicHooksMetaTokenRoute: ApiPublicHooksMetaTokenRoute,
  ApiPublicHooksWordpressTokenRoute: ApiPublicHooksWordpressTokenRoute,
  ApiPublicOauthGoogleAdsCallbackRoute: ApiPublicOauthGoogleAdsCallbackRoute,
  ApiPublicOauthMetaCallbackRoute: ApiPublicOauthMetaCallbackRoute,
  ApiPublicTwilioTokenRecordingRoute: ApiPublicTwilioTokenRecordingRoute,
  ApiPublicTwilioTokenSmsRoute: ApiPublicTwilioTokenSmsRoute,
  ApiPublicTwilioTokenStatusRoute: ApiPublicTwilioTokenStatusRoute,
  ApiPublicTwilioTokenVoiceRoute: ApiPublicTwilioTokenVoiceRoute,
  ApiPublicTwilioTokenVoiceOutboundRoute:
    ApiPublicTwilioTokenVoiceOutboundRoute,
  ApiPublicTwilioTokenVoiceStatusRoute: ApiPublicTwilioTokenVoiceStatusRoute,
  ApiPublicTwilioTokenVoicemailRoute: ApiPublicTwilioTokenVoicemailRoute,
  ApiPublicTwilioTokenWhatsappRoute: ApiPublicTwilioTokenWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
